### ISSUE TITLE
Unable to Create multiple model with the same serving runtime using ODH for inference graph

### ISSUE THREAD

**Issue by R3hankhan123** [opendatahub-io/kserve#486]
/kind bug

**What steps did you take and what happened:**
When I am trying to deploy two to pytorch model using ODH Dashboard, I am getting the following error
```
Danger alert:Error creating model server
admission webhook "servingruntime.kserve-webhook-server.validator" denied the request: same priority assigned for the model format pytorch in the servingruntimes maskrcnn and densenet161 in namespace kserve-torchserve
```
I am using the following serving runtime
```
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    openshift.io/display-name: TorchServe Model Server
  labels:
    opendatahub.io/dashboard: "true"
  name: kserve-torchserve
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - image: quay.io/ksdeekshith/torchserve:s390x-cpu-final
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 4Gi
      name: kserve-container
      env:
        - name: TS_CONFIG_FILE
          value: /mnt/models/config/config.properties
        - name: TEMP
          value: /tmp
  multiModel: false
  supportedModelFormats:
    - name: pytorch
      version: "1"
      priority: 2
      autoSelect: true
    - name: pytorch
      version: "2"
      priority: 3
      autoSelect: true
  protocolVersions:
    - v1
    - v2
    - grpc-v2
```

For maskrcnn i have deployed using pytorch 1 and for densenet161 i am trying to deploy via pytorch 2

<img width="889" alt="Image" src="https://github.com/user-attachments/assets/19aeacef-d3e4-4b2d-ab1c-e5baf73c2f31" />

Is there any way to change the priority of the model
**What did you expect to happen:**
The other model needed to be deployed to allow to create sequence type inference graph.

**Environment:**

- Istio Version: v2.6.4-0 (using service mesh)
- Knative Version: v1.35.0
- KServe Version: v0.14
- Open Data Hub version: 2.21.0
- Deployment Environment: on prem
- OpenShift version: (use `kubectl version`): v4.15.43
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8.9 (Ootpa)
