### ISSUE TITLE
Enable SVC in RAW mode when installing KServe Serverless

### ISSUE THREAD

**Issue by smhgit** [opendatahub-io/kserve#534]
- Install KServe serverless
- Create ISV in Raw mode

=> SVC is not workiing. Only direct access to the POD with port. 

The reason is that the SVC is headless. Here is an example:

```
kind: Service
apiVersion: v1
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  name: m6608c280011011-predictor
  labels:
    app: isvc.m6608c280011011-predictor
    component: predictor
    networking.kserve.dev/visibility: cluster-local
    serving.kserve.io/inferenceservice: m6608c280011011
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: m6608c280011011-predictor
      protocol: TCP
      port: 80
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - None
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: isvc.m6608c280011011-predictor
status:
  loadBalancer: {}
```
